export const PROVIDER_LOADER = 'PROVIDER/PROVIDER_LOADER';
export const PROVIDER_FAILURE = 'PROVIDER/PROVIDER_FAILURE';

export const CREATE_PROVIDER_SUCCESS = 'PROVIDER/CREATE_PROVIDER_SUCCESS';

export const GET_PROVIDERS_SUCCESS = 'PROVIDER/GET_PROVIDERS_SUCCESS';
export const GET_SINGLE_PROVIDER_SUCCESS =
  'PROVIDER/GET_SINGLE_PROVIDER_SUCCESS';

export const EDIT_PROVIDER_SUCCESS = 'PROVIDER/EDIT_PROVIDER_SUCCESS';
export const DELETE_PROVIDER_SUCCESS = 'PROVIDER/DELETE_PROVIDER_SUCCESS';
export const GET_CHECKED_PROVIDERS = 'PROVIDER/GET_CHECKED_PROVIDERS';
export const EDIT_CHECKED_PROVIDERS = 'PROVIDER/EDIT_CHECKED_PROVIDERS';
export const RESET_CONFIRM = 'PROVIDER/RESET_CONFIRM';
