export const CLIENT_LOADER = 'CLIENT/CLIENT_LOADER';
export const CLIENT_FAILURE = 'CLIENT/CLIENT_FAILURE';

export const CREATE_CLIENT_SUCCESS = 'CLIENT/CREATE_CLIENT_SUCCESS';

export const GET_CLIENTS_SUCCESS = 'CLIENT/GET_CLIENTS_SUCCESS';
export const GET_SINGLE_CLIENT_SUCCESS = 'CLIENT/GET_SINGLE_CLIENT_SUCCESS';

export const EDIT_CLIENT_SUCCESS = 'CLIENT/EDIT_CLIENT_SUCCESS';
export const DELETE_CLIENT_SUCCESS = 'CLIENT/DELETE_CLIENT_SUCCESS';
export const RESET_CLIENT = 'CLIENT/RESET_CLIENT';
export const RESET_MODAL = 'CLIENT/RESET_MODAL';
